apiVersion: v1
kind: Secret
metadata:
  name: sitentl-secrets
  namespace: srv
type: Opaque
stringData:
  DB_USER: "sa"
  DB_PASSWORD: "@Cisne38"
  DB_SERVER: "177.136.203.111"
  DB_PORT: "2866"
  DB_NAME: "stc"
